# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: J. Hogue is Highchair designhaus
email: jh@highchairdesign.com
company: Highchair designhaus
description: >- # this means to ignore newlines until "baseurl:"
  J. Hogue has over 20 years of experience in design and user experience. He is currently Director, Experience Design at Oomph, leading a team of digital platform experts with strategic thinking, cutting-edge UX practices, and visual design. I have worked with all sizes of business, from national brands to local non-profits, in the health, higher education, cultural institution, and new technology sectors.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.highchairdesign.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM 
  syntax_highlighter: rouge

# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:year/:month/:title:output_ext
relative_permalinks: false

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
  notes:
    output: true
    permalink: /note/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: item
  - scope:
      path: ""
      type: "notes"
    values:
      layout: note

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - html-markdown-conversion.md
  - kramdown.md
  - LICENSE
  - README.md
  - source/
